"""One-click PDF 'Commander's Briefing' — a printable A4 enforcement brief
(KPIs, hotspot map, top zones, patrol route, station allocation)."""
import io
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

NAVY, INK, MUTE, RED, GRN, SKY = "#0e2a44", "#11202f", "#5b6b86", "#ef4444", "#1aa179", "#1d6fb8"


def build_pdf(M, cells, zones, routed, ward, day_label="Today") -> bytes:
    buf = io.BytesIO()
    with PdfPages(buf) as pdf:
        fig = plt.figure(figsize=(8.27, 11.69))                 # A4 portrait
        fig.patch.set_facecolor("white")
        gs = fig.add_gridspec(5, 2, height_ratios=[0.6, 2.0, 1.7, 1.7, 0.25],
                              hspace=0.45, wspace=0.18, left=0.07, right=0.95, top=0.95, bottom=0.04)

        # header
        ax = fig.add_subplot(gs[0, :]); ax.axis("off")
        ax.text(0, 0.7, "ParkSight — Commander's Briefing", fontsize=18, fontweight="bold", color=INK)
        ax.text(0, 0.18, f"Parking-Induced Congestion · Bengaluru · {day_label}", fontsize=10, color=MUTE)
        c = M.get("cost", {}); v = M.get("validation", {})
        kp = (f"Hotspots {M['n_cells']:,}   |   Chronic {M['n_chronic_cells']}   |   "
              f"Cost ₹{c.get('annual_cost_cr','?')} cr/yr   |   "
              f"Forecast R² {M.get('holdout',{}).get('holdout_r2_cellhour','?')}   |   "
              f"Validation {v.get('neighbourhood_lift','?')}×")
        ax.text(0, -0.35, kp, fontsize=9.5, color=SKY, fontweight="bold")

        # hotspot map (scatter)
        ax = fig.add_subplot(gs[1, :])
        sc = ax.scatter(cells.lon, cells.lat, c=cells.CIS, cmap="inferno", s=8 + cells.CIS/3,
                        alpha=0.8, linewidths=0)
        ax.plot(routed.lon, routed.lat, "-o", color="#0a7", lw=1.3, ms=3, label="patrol route")
        ax.set_title("Congestion-impact hotspots & today's patrol route", fontsize=11, fontweight="bold")
        ax.set_xticks([]); ax.set_yticks([]); ax.legend(loc="upper right", fontsize=8)
        plt.colorbar(sc, ax=ax, shrink=0.7, label="Impact")

        # top zones
        ax = fig.add_subplot(gs[2, 0])
        z = zones.head(10)[::-1]
        ax.barh(z.name.astype(str), z.CIS_100, color=RED)
        ax.set_title("Top-10 enforcement zones", fontsize=10, fontweight="bold")
        ax.tick_params(labelsize=7); ax.set_xlabel("Impact /100", fontsize=8)

        # route stops
        ax = fig.add_subplot(gs[2, 1]); ax.axis("off")
        ax.set_title(f"Patrol route — {len(routed)} stops", fontsize=10, fontweight="bold", loc="left")
        lines = [f"{int(r.stop):>2}.  {str(r.name)[:26]:<26}  CIS {r.CIS_100:>4}"
                 for r in routed.head(15).itertuples()]
        ax.text(0, 0.95, "\n".join(lines), fontsize=7.6, family="monospace", va="top", color=INK)

        # ward allocation
        ax = fig.add_subplot(gs[3, 0])
        w = ward.head(8)[::-1]
        ax.barh(w.police_station.astype(str), w.recommended_units, color=SKY)
        ax.set_title("Recommended units by station", fontsize=10, fontweight="bold")
        ax.tick_params(labelsize=7); ax.set_xlabel("units", fontsize=8)

        # offenders / trends summary
        ax = fig.add_subplot(gs[3, 1]); ax.axis("off")
        o = M.get("offenders", {}); tr = M.get("trends", {}); p = M.get("poi", {})
        txt = (f"REPEAT OFFENDERS\n  {o.get('vio_from_repeat_%','?')}% of violations from repeat\n"
               f"  vehicles; worst {o.get('max_by_one_vehicle','?')}×\n\n"
               f"POST-ENFORCEMENT TREND\n  {tr.get('improving','?')} improving · "
               f"{tr.get('worsening','?')} worsening\n\n"
               f"CONTEXT\n  {p.get('pct_top_near_poi','?')}% of hotspots near\n  metro/market/mall")
        ax.text(0, 0.98, txt, fontsize=8.5, va="top", color=INK)

        ax = fig.add_subplot(gs[4, :]); ax.axis("off")
        ax.text(0, 0.5, "Generated by ParkSight · prioritise the worst ~7% of cells to address 80% of impact.",
                fontsize=8, color=MUTE, style="italic")
        pdf.savefig(fig, facecolor="white"); plt.close(fig)
    return buf.getvalue()
